/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package repop2_joselagos;

import java.io.IOException;
import java.util.HashSet;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tonye
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);

        DefaultComboBoxModel model = (DefaultComboBoxModel) cb_Tipo.getModel();

        model.addElement("Hack Regular");
        model.addElement("Super Hack");
        cb_Tipo.setModel(model);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Risklvl = new javax.swing.ButtonGroup();
        jd_ModR = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_ModCodigoR = new javax.swing.JFormattedTextField();
        rdb_mod1 = new javax.swing.JRadioButton();
        rdb_Mod2 = new javax.swing.JRadioButton();
        rdb_Mod3 = new javax.swing.JRadioButton();
        rdb_Mod4 = new javax.swing.JRadioButton();
        rdb_Mod5 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        ModRlvl = new javax.swing.ButtonGroup();
        jd_ModS = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_ModCodigoS = new javax.swing.JFormattedTextField();
        rdb_Mod6s = new javax.swing.JRadioButton();
        rdb_Mod7s = new javax.swing.JRadioButton();
        rdb_Mod8s = new javax.swing.JRadioButton();
        rdb_Mod9s = new javax.swing.JRadioButton();
        rdb_Mod10s = new javax.swing.JRadioButton();
        btn_Super = new javax.swing.JButton();
        riskS = new javax.swing.ButtonGroup();
        jd_Simulacion = new javax.swing.JDialog();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        cb_SimulacionR = new javax.swing.JComboBox<>();
        pb_BarraRegular = new javax.swing.JProgressBar();
        jButton3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        cb_Simulacions = new javax.swing.JComboBox<>();
        pb_BarraSuper = new javax.swing.JProgressBar();
        jButton2 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cb_Tipo = new javax.swing.JComboBox<>();
        tf_Codigo = new javax.swing.JFormattedTextField();
        rdb_1 = new javax.swing.JRadioButton();
        rdb_2 = new javax.swing.JRadioButton();
        rdb_3 = new javax.swing.JRadioButton();
        rdb_4 = new javax.swing.JRadioButton();
        rdb_5 = new javax.swing.JRadioButton();
        btn_Guardar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_Regulaes = new javax.swing.JTable();
        btn_EliminarRHack = new javax.swing.JButton();
        btn_ModRHack = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_Super = new javax.swing.JTable();
        btn_ModSHack = new javax.swing.JButton();
        btn_EliminarSHack = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        jd_ModR.setTitle("Modificar");

        jLabel5.setText("Codigo");

        jLabel6.setText("Nivel de Riesgo");

        tf_ModCodigoR.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#########################"))));

        ModRlvl.add(rdb_mod1);
        rdb_mod1.setText("1");

        Risklvl.add(rdb_Mod2);
        rdb_Mod2.setText("2");

        ModRlvl.add(rdb_Mod3);
        rdb_Mod3.setText("3");
        rdb_Mod3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_Mod3ActionPerformed(evt);
            }
        });

        ModRlvl.add(rdb_Mod4);
        rdb_Mod4.setText("4");

        ModRlvl.add(rdb_Mod5);
        rdb_Mod5.setText("5");

        jButton1.setText("Guardar Cambios");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_ModRLayout = new javax.swing.GroupLayout(jd_ModR.getContentPane());
        jd_ModR.getContentPane().setLayout(jd_ModRLayout);
        jd_ModRLayout.setHorizontalGroup(
            jd_ModRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ModRLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jd_ModRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jd_ModRLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_ModCodigoR, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_ModRLayout.createSequentialGroup()
                        .addComponent(rdb_mod1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdb_Mod2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_ModRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jd_ModRLayout.createSequentialGroup()
                                .addComponent(rdb_Mod3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdb_Mod4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdb_Mod5)))))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        jd_ModRLayout.setVerticalGroup(
            jd_ModRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ModRLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jd_ModRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_ModCodigoR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_ModRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdb_mod1)
                    .addComponent(rdb_Mod2)
                    .addComponent(rdb_Mod3)
                    .addComponent(rdb_Mod4)
                    .addComponent(rdb_Mod5))
                .addGap(54, 54, 54)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jd_ModS.setTitle("Modificar");

        jLabel7.setText("Codigo");

        jLabel8.setText("Nivel de Riesgo");

        tf_ModCodigoS.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#########################"))));

        riskS.add(rdb_Mod6s);
        rdb_Mod6s.setText("6");

        riskS.add(rdb_Mod7s);
        rdb_Mod7s.setText("7");

        riskS.add(rdb_Mod8s);
        rdb_Mod8s.setText("8");
        rdb_Mod8s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_Mod8sActionPerformed(evt);
            }
        });

        riskS.add(rdb_Mod9s);
        rdb_Mod9s.setText("9");
        rdb_Mod9s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_Mod9sActionPerformed(evt);
            }
        });

        riskS.add(rdb_Mod10s);
        rdb_Mod10s.setText("10");

        btn_Super.setText("Guardar Cambios");
        btn_Super.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SuperMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_ModSLayout = new javax.swing.GroupLayout(jd_ModS.getContentPane());
        jd_ModS.getContentPane().setLayout(jd_ModSLayout);
        jd_ModSLayout.setHorizontalGroup(
            jd_ModSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ModSLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jd_ModSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jd_ModSLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_ModCodigoS, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_ModSLayout.createSequentialGroup()
                        .addComponent(rdb_Mod6s)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdb_Mod7s)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_ModSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Super, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jd_ModSLayout.createSequentialGroup()
                                .addComponent(rdb_Mod8s)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdb_Mod9s)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdb_Mod10s)))))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        jd_ModSLayout.setVerticalGroup(
            jd_ModSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ModSLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jd_ModSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_ModCodigoS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_ModSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdb_Mod6s)
                    .addComponent(rdb_Mod7s)
                    .addComponent(rdb_Mod8s)
                    .addComponent(rdb_Mod9s)
                    .addComponent(rdb_Mod10s))
                .addGap(54, 54, 54)
                .addComponent(btn_Super, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jd_Simulacion.setTitle("Simulacion");

        pb_BarraRegular.setStringPainted(true);

        jButton3.setText("Test");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pb_BarraRegular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(cb_SimulacionR, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(235, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(cb_SimulacionR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(pb_BarraRegular, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        jTabbedPane3.addTab("Simulacion Hackeo Regular", jPanel5);

        pb_BarraSuper.setStringPainted(true);

        jButton2.setText("Test");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pb_BarraSuper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(cb_Simulacions, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(244, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(cb_Simulacions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(pb_BarraSuper, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jTabbedPane3.addTab("Simulacion Super Hackeo", jPanel6);

        javax.swing.GroupLayout jd_SimulacionLayout = new javax.swing.GroupLayout(jd_Simulacion.getContentPane());
        jd_Simulacion.getContentPane().setLayout(jd_SimulacionLayout);
        jd_SimulacionLayout.setHorizontalGroup(
            jd_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        jd_SimulacionLayout.setVerticalGroup(
            jd_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lab Reposicion");

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jLabel1.setText("Codigo:");

        jLabel2.setText("Nivel de Riesgo");

        jLabel3.setText("Tipo:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Creador de Hacks");

        cb_Tipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_TipoItemStateChanged(evt);
            }
        });

        tf_Codigo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#########################"))));

        Risklvl.add(rdb_1);
        rdb_1.setText("1");

        Risklvl.add(rdb_2);
        rdb_2.setText("2");

        Risklvl.add(rdb_3);
        rdb_3.setSelected(true);
        rdb_3.setText("3");

        Risklvl.add(rdb_4);
        rdb_4.setText("4");

        Risklvl.add(rdb_5);
        rdb_5.setText("5");

        btn_Guardar.setText("Guardar");
        btn_Guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_GuardarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                                .addComponent(btn_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(rdb_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdb_2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdb_3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdb_4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdb_5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel4)))
                .addGap(85, 85, 85))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cb_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdb_1)
                    .addComponent(rdb_2)
                    .addComponent(rdb_3)
                    .addComponent(rdb_4)
                    .addComponent(rdb_5))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear Hack", jPanel1);

        jt_Regulaes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nivel de Riesgo", "Hackeos Exitosos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jt_Regulaes);

        btn_EliminarRHack.setText("Eliminar");
        btn_EliminarRHack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_EliminarRHackMouseClicked(evt);
            }
        });

        btn_ModRHack.setText("Modificar");
        btn_ModRHack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ModRHackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_EliminarRHack, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(112, 112, 112)
                    .addComponent(btn_ModRHack, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(365, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btn_EliminarRHack, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(228, Short.MAX_VALUE)
                    .addComponent(btn_ModRHack, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)))
        );

        jTabbedPane2.addTab("Hacks Regulares", jPanel3);

        jt_Super.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nivel de Riesgo", "Hackeos Fallidos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jt_Super);

        btn_ModSHack.setText("Modificar");
        btn_ModSHack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ModSHackMouseClicked(evt);
            }
        });

        btn_EliminarSHack.setText("Eliminar");
        btn_EliminarSHack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_EliminarSHackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(btn_ModSHack, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btn_EliminarSHack, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_ModSHack, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(btn_EliminarSHack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Super Hacks", jPanel4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listar/Modificar", jPanel2);

        jMenu1.setText("Simulación");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_TipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_TipoItemStateChanged
        String tipo;
        tipo = (String) cb_Tipo.getSelectedItem();

        if ("Super Hack".equals(tipo)) {
            rdb_1.setText("6");
            rdb_2.setText("7");
            rdb_3.setText("8");
            rdb_4.setText("9");
            rdb_5.setText("10");
        } else {
            rdb_1.setText("1");
            rdb_2.setText("2");
            rdb_3.setText("3");
            rdb_4.setText("4");
            rdb_5.setText("5");
        }
    }//GEN-LAST:event_cb_TipoItemStateChanged

    private void btn_GuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_GuardarMouseClicked
        int codigo = Integer.parseInt(tf_Codigo.getText());
        int riesgo = 0;

        if (cb_Tipo.getSelectedItem().equals("Hack Regular")) {
            if (rdb_1.isSelected()) {
                riesgo = 1;
            } else if (rdb_2.isSelected()) {
                riesgo = 2;
            } else if (rdb_3.isSelected()) {
                riesgo = 3;
            } else if (rdb_4.isSelected()) {
                riesgo = 4;
            } else if (rdb_5.isSelected()) {
                riesgo = 5;
            }
        } else {
            if (rdb_1.isSelected()) {
                riesgo = 6;
            } else if (rdb_2.isSelected()) {
                riesgo = 7;
            } else if (rdb_3.isSelected()) {
                riesgo = 8;
            } else if (rdb_4.isSelected()) {
                riesgo = 9;
            } else if (rdb_5.isSelected()) {
                riesgo = 10;
            }
        }
        AdminHackeo h = new AdminHackeo("./Regulares.txt");
        AdminHackeo hs = new AdminHackeo("./Super.txt");

        if (cb_Tipo.getSelectedItem().equals("Hack Regular")) {

            try {
                h.leerArchivoRegular();

                Regulares p = new Regulares(codigo, riesgo);
                h.getHacks_R().add(p);
                h.crearArchivoRegular();
            } catch (IOException ex) {

            }

        } else {
            try {
                hs.leerArchivoSuper();

                Super sh = new Super(codigo, riesgo);
                hs.getHacks_S().add(sh);
                hs.crearArchivoSuper();
            } catch (IOException ex) {

            }
        }
        JOptionPane.showMessageDialog(this, "El hackeo ha sido guardado");
        tf_Codigo.setText("");
        rdb_1.setSelected(false);
        rdb_2.setSelected(false);
        rdb_3.setSelected(true);
        rdb_4.setSelected(false);
        rdb_5.setSelected(false);

    }//GEN-LAST:event_btn_GuardarMouseClicked

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        AdminHackeo h = new AdminHackeo("./Regulares.txt");
        AdminHackeo hs = new AdminHackeo("./Super.txt");
        h.leerArchivoRegular();
        hs.leerArchivoSuper();
        
        jt_Regulaes.setModel(new javax.swing.table.DefaultTableModel(new Object[][]{}, new String[]{"Codigo", "Nivel de Riesgo", "Hackeos Exitosos"}
        ) {
            Class[] types = new Class[]{
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        
        jt_Super.setModel(new javax.swing.table.DefaultTableModel(new Object[][]{}, new String[]{"Codigo", "Nivel de Riesgo", "Hackeos Fallidos"}
        ) {
            Class[] types = new Class[]{
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        
        for (Regulares r : h.getHacks_R()) {
            DefaultTableModel modelo = (DefaultTableModel) jt_Regulaes.getModel();
            Object[] newrow = {r.getCodigo(), r.getRiesgo(), r.getExito()};
            modelo.addRow(newrow);
            jt_Regulaes.setModel(modelo);
        }
        for (Super s : hs.getHacks_S()) {
            DefaultTableModel modelo = (DefaultTableModel) jt_Super.getModel();
            Object[] newrow = {s.getCodigo(), s.getRiesgo(), s.getFallidos()};
            modelo.addRow(newrow);
            jt_Super.setModel(modelo);
        }

    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void btn_ModSHackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ModSHackMouseClicked
        AdminHackeo h = new AdminHackeo("./Super.txt");
        h.leerArchivoSuper();

        DefaultTableModel model = (DefaultTableModel) jt_Super.getModel();

        for (int i = 0; i < h.getHacks_S().size(); i++) {
            if (i == jt_Super.getSelectedRow()) {
                flag = i;
                tf_ModCodigoS.setText(h.getHacks_S().get(i).toString());
                int aux = h.getHacks_S().get(i).getRiesgo();
                switch (aux) {
                    case 6: {
                        rdb_Mod6s.setSelected(true);
                        break;
                    }
                    case 7: {
                        rdb_Mod7s.setSelected(true);
                        break;
                    }
                    case 8: {
                        rdb_Mod8s.setSelected(true);
                        break;
                    }
                    case 9: {
                        rdb_Mod9s.setSelected(true);
                        break;
                    }
                    case 10: {
                        rdb_Mod10s.setSelected(true);
                        break;
                    }
                }
            }
        }

        jd_ModS.setModal(true);
        jd_ModS.pack();
        jd_ModS.setLocationRelativeTo(null);

        jd_ModS.setVisible(true);
    }//GEN-LAST:event_btn_ModSHackMouseClicked

    private void btn_ModRHackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ModRHackMouseClicked
        AdminHackeo h = new AdminHackeo("./Regulares.txt");
        h.leerArchivoRegular();

        DefaultTableModel model = (DefaultTableModel) jt_Regulaes.getModel();

        for (int i = 0; i < h.getHacks_R().size(); i++) {
            if (i == jt_Regulaes.getSelectedRow()) {
                flag = i;
                tf_ModCodigoR.setText(h.getHacks_R().get(i).toString());
                int aux = h.getHacks_R().get(i).getRiesgo();
                switch (aux) {
                    case 1: {
                        rdb_mod1.setSelected(true);
                        break;
                    }
                    case 2: {
                        rdb_Mod2.setSelected(true);
                        break;
                    }
                    case 3: {
                        rdb_Mod3.setSelected(true);
                        break;
                    }
                    case 4: {
                        rdb_Mod4.setSelected(true);
                        break;
                    }
                    case 5: {
                        rdb_Mod5.setSelected(true);
                        break;
                    }
                }
            }
        }

        jd_ModR.setModal(true);
        jd_ModR.pack();
        jd_ModR.setLocationRelativeTo(null);

        jd_ModR.setVisible(true);
    }//GEN-LAST:event_btn_ModRHackMouseClicked

    private void rdb_Mod3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_Mod3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdb_Mod3ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        AdminHackeo h = new AdminHackeo("./Regulares.txt");
        h.leerArchivoRegular();
        try {

            int codigo = Integer.parseInt(tf_ModCodigoR.getText());
            int riesgo = 0;
            if (rdb_mod1.isSelected()) {
                riesgo = 1;
            } else if (rdb_Mod2.isSelected()) {
                riesgo = 2;
            } else if (rdb_Mod3.isSelected()) {
                riesgo = 3;
            } else if (rdb_Mod4.isSelected()) {
                riesgo = 4;
            } else if (rdb_Mod5.isSelected()) {
                riesgo = 5;
            }

            h.getHacks_R().get(flag).setCodigo(codigo);
            h.getHacks_R().get(flag).setRiesgo(riesgo);
            h.crearArchivoRegular();

        } catch (IOException ex) {

        }

        jt_Regulaes.setModel(new javax.swing.table.DefaultTableModel(new Object[][]{}, new String[]{"Codigo", "Nivel de Riesgo", "Hackeos Exitosos"}
        ) {
            Class[] types = new Class[]{
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        for (Regulares r : h.getHacks_R()) {
            DefaultTableModel modelo = (DefaultTableModel) jt_Regulaes.getModel();
            Object[] newrow = {r.getCodigo(), r.getRiesgo(), r.getExito()};
            modelo.addRow(newrow);
            jt_Regulaes.setModel(modelo);
        }
        JOptionPane.showMessageDialog(this, "El sistema de hackeo ha sido modificado");
        jd_ModR.dispose();

    }//GEN-LAST:event_jButton1MouseClicked

    private void btn_EliminarRHackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EliminarRHackMouseClicked
        AdminHackeo h = new AdminHackeo("./Regulares.txt");
        h.leerArchivoRegular();

        DefaultTableModel model = (DefaultTableModel) jt_Regulaes.getModel();

        for (int i = 0; i < h.getHacks_R().size(); i++) {
            if (i == jt_Regulaes.getSelectedRow()) {
                try {
                    h.getHacks_R().remove(i);
                    h.crearArchivoRegular();
                } catch (IOException ex) {

                }
            }
        }
        jt_Regulaes.setModel(new javax.swing.table.DefaultTableModel(new Object[][]{}, new String[]{"Codigo", "Nivel de Riesgo", "Hackeos Exitosos"}
        ) {
            Class[] types = new Class[]{
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        for (Regulares r : h.getHacks_R()) {
            DefaultTableModel modelo = (DefaultTableModel) jt_Regulaes.getModel();
            Object[] newrow = {r.getCodigo(), r.getRiesgo(), r.getExito()};
            modelo.addRow(newrow);
            jt_Regulaes.setModel(modelo);
        }
        JOptionPane.showMessageDialog(this, "El sistema de hackeo ha sido eliminado");
    }//GEN-LAST:event_btn_EliminarRHackMouseClicked

    private void rdb_Mod8sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_Mod8sActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdb_Mod8sActionPerformed

    private void btn_SuperMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SuperMouseClicked
        AdminHackeo h = new AdminHackeo("./Super.txt");
        h.leerArchivoSuper();
        try {

            int codigo = Integer.parseInt(tf_ModCodigoS.getText());
            int riesgo = 0;
            if (rdb_Mod6s.isSelected()) {
                riesgo = 6;
            } else if (rdb_Mod7s.isSelected()) {
                riesgo = 7;
            } else if (rdb_Mod8s.isSelected()) {
                riesgo = 8;
            } else if (rdb_Mod9s.isSelected()) {
                riesgo = 9;
            } else if (rdb_Mod10s.isSelected()) {
                riesgo = 10;
            }

            h.getHacks_S().get(flag).setCodigo(codigo);
            h.getHacks_S().get(flag).setRiesgo(riesgo);
            h.crearArchivoSuper();

        } catch (IOException ex) {

        }

        jt_Super.setModel(new javax.swing.table.DefaultTableModel(new Object[][]{}, new String[]{"Codigo", "Nivel de Riesgo", "Hackeos Fallidos"}
        ) {
            Class[] types = new Class[]{
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        for (Super r : h.getHacks_S()) {
            DefaultTableModel modelo = (DefaultTableModel) jt_Super.getModel();
            Object[] newrow = {r.getCodigo(), r.getRiesgo(), r.getFallidos()};
            modelo.addRow(newrow);
            jt_Super.setModel(modelo);
        }
        JOptionPane.showMessageDialog(this, "El sistema de hackeo ha sido modificado");
        jd_ModS.dispose();
    }//GEN-LAST:event_btn_SuperMouseClicked

    private void rdb_Mod9sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_Mod9sActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdb_Mod9sActionPerformed

    private void btn_EliminarSHackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EliminarSHackMouseClicked
        AdminHackeo h = new AdminHackeo("./Super.txt");
        h.leerArchivoSuper();

        DefaultTableModel model = (DefaultTableModel) jt_Super.getModel();

        for (int i = 0; i < h.getHacks_S().size(); i++) {
            if (i == jt_Super.getSelectedRow()) {
                try {
                    h.getHacks_S().remove(i);
                    h.crearArchivoSuper();
                } catch (IOException ex) {

                }
            }
        }
        jt_Super.setModel(new javax.swing.table.DefaultTableModel(new Object[][]{}, new String[]{"Codigo", "Nivel de Riesgo", "Hackeos Fallidos"}
        ) {
            Class[] types = new Class[]{
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        for (Super r : h.getHacks_S()) {
            DefaultTableModel modelo = (DefaultTableModel) jt_Super.getModel();
            Object[] newrow = {r.getCodigo(), r.getRiesgo(), r.getFallidos()};
            modelo.addRow(newrow);
            jt_Super.setModel(modelo);
        }
        JOptionPane.showMessageDialog(this, "El sistema de hackeo ha sido eliminado");
    }//GEN-LAST:event_btn_EliminarSHackMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        AdminHackeo sh = new AdminHackeo("./Super.txt");
        sh.leerArchivoSuper();
        AdminHackeo h = new AdminHackeo("./Regulares.txt");
        h.leerArchivoRegular();

        DefaultComboBoxModel mod1 = (DefaultComboBoxModel) cb_SimulacionR.getModel();
        DefaultComboBoxModel mod2 = (DefaultComboBoxModel) cb_Simulacions.getModel();

        for (Regulares r : h.getHacks_R()) {
            mod1.addElement(r);
        }
        cb_SimulacionR.setModel(mod1);

        for (Super s : sh.getHacks_S()) {
            mod2.addElement(s);
        }
        cb_Simulacions.setModel(mod2);

        jd_Simulacion.setModal(true);
        jd_Simulacion.pack();
        jd_Simulacion.setLocationRelativeTo(null);

        jd_Simulacion.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        Random random = new Random();
        AdminHackeo h = new AdminHackeo("./Regular.txt");
        h.leerArchivoRegular();
        DefaultComboBoxModel mod1 = (DefaultComboBoxModel) cb_SimulacionR.getModel();
        Regulares hack = (Regulares) mod1.getSelectedItem();

        int x = random.nextInt(6 - 1)+ 1;

        if (x == hack.getRiesgo()) {
            JOptionPane.showMessageDialog(this, "El hackeo se ha detenido");
        } else {
            
            int num_c = 0;
            String caracteres = JOptionPane.showInputDialog("Ingrese los caracteres con los que desea probar el hackeo");
            for (int i = 0; i < caracteres.length(); i++) {
                num_c++;
            }
            
            for (int i = 0; i < h.getHacks_R().size(); i++) {
                if(h.getHacks_R().get(i).getCodigo() == hack.getCodigo()){
                    try {
                        h.getHacks_R().get(i).setExito(h.getHacks_R().get(i).getExito()+1);
                        h.crearArchivoSuper();
                    } catch (IOException ex) {
                        
                    }
                }
            }
            
            int tiempo = num_c*2;
            pb_BarraRegular.setMaximum(tiempo);
            
            admin = new AdminProgress(pb_BarraRegular, tiempo);
            
            admin.start();
            
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        Random random = new Random();
        AdminHackeo h = new AdminHackeo("./Super.txt");
        h.leerArchivoSuper();
        DefaultComboBoxModel mod = (DefaultComboBoxModel) cb_Simulacions.getModel();
        Super hack = (Super) mod.getSelectedItem();

        int x = random.nextInt(11 - 6)+ 6;

        System.out.println(x);
        if (x == hack.getRiesgo()) {
            JOptionPane.showMessageDialog(this, "El hackeo se ha detenido");
            for (int i = 0; i < h.getHacks_S().size(); i++) {
                if(h.getHacks_S().get(i).getCodigo() == hack.getCodigo()){
                    try {
                        h.getHacks_S().get(i).setFallidos(h.getHacks_S().get(i).getFallidos()+1);
                        h.crearArchivoSuper();
                    } catch (IOException ex) {
                        
                    }
                }
            }
            
        } else {
            int num_c = 0;
            String caracteres = JOptionPane.showInputDialog("Ingrese los caracteres con los que desea probar el hackeo");
            for (int i = 0; i < caracteres.length(); i++) {
                num_c++;
            }
            pb_BarraSuper.setMaximum(num_c);
            
            admin = new AdminProgress(pb_BarraSuper, num_c);
            
            admin.start();          
            
        }
    }//GEN-LAST:event_jButton2MouseClicked

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup ModRlvl;
    private javax.swing.ButtonGroup Risklvl;
    private javax.swing.JButton btn_EliminarRHack;
    private javax.swing.JButton btn_EliminarSHack;
    private javax.swing.JButton btn_Guardar;
    private javax.swing.JButton btn_ModRHack;
    private javax.swing.JButton btn_ModSHack;
    private javax.swing.JButton btn_Super;
    private javax.swing.JComboBox<String> cb_SimulacionR;
    private javax.swing.JComboBox<String> cb_Simulacions;
    private javax.swing.JComboBox<String> cb_Tipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JDialog jd_ModR;
    private javax.swing.JDialog jd_ModS;
    private javax.swing.JDialog jd_Simulacion;
    private javax.swing.JTable jt_Regulaes;
    private javax.swing.JTable jt_Super;
    private javax.swing.JProgressBar pb_BarraRegular;
    private javax.swing.JProgressBar pb_BarraSuper;
    private javax.swing.JRadioButton rdb_1;
    private javax.swing.JRadioButton rdb_2;
    private javax.swing.JRadioButton rdb_3;
    private javax.swing.JRadioButton rdb_4;
    private javax.swing.JRadioButton rdb_5;
    private javax.swing.JRadioButton rdb_Mod10s;
    private javax.swing.JRadioButton rdb_Mod2;
    private javax.swing.JRadioButton rdb_Mod3;
    private javax.swing.JRadioButton rdb_Mod4;
    private javax.swing.JRadioButton rdb_Mod5;
    private javax.swing.JRadioButton rdb_Mod6s;
    private javax.swing.JRadioButton rdb_Mod7s;
    private javax.swing.JRadioButton rdb_Mod8s;
    private javax.swing.JRadioButton rdb_Mod9s;
    private javax.swing.JRadioButton rdb_mod1;
    private javax.swing.ButtonGroup riskS;
    private javax.swing.JFormattedTextField tf_Codigo;
    private javax.swing.JFormattedTextField tf_ModCodigoR;
    private javax.swing.JFormattedTextField tf_ModCodigoS;
    // End of variables declaration//GEN-END:variables
    int flag = 0;
    AdminProgress admin;
}
